name: Python Application CI/CD

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verificar dependências
        run: pip check

      - name: Lint com flake8
        run: |
          flake8 . --max-complexity=10 --max-line-length=127 --select=E9,F63,F7,F82 --statistics

      - name: Testar com pytest e gerar relatórios de cobertura
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml --cov-fail-under=80 tests -vv

      - name: Enviar relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov

      - name: Publicar cobertura no Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
