# Este workflow instala dependências Python, executa testes, verifica o código com linting
# e gera relatórios de cobertura de forma automatizada.
# Para mais informações, consulte: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application CI/CD

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

permissions:
  contents: read  # Permissão necessária para o checkout do repositório

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]  # Especifica a versão do Python a ser utilizada, pode ser expandido para suportar múltiplas versões

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint com flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Testar com pytest e gerar relatórios de cobertura
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml tests -vv

      - name: Enviar relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
